// App-level type aliases.
// Domain models are now generated by Prisma — import from '@prisma/client'.
// These remain for backward compatibility with existing dashboard components
// and will be phased out as the UI migrates to real data.

export interface BillDetails {
  id: string;
  name: string;
  purpose: string;
  amount: number;
  status: string;
}

// Re-export the pure algorithm types for convenience
export type { Balance, Transaction } from '@/lib/debt-algorithm';
